server:
  port: 8000
spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
  main:
    web-application-type: reactive
  redis:
    host: localhost
    port: 6379
  application:
    name: apigateway-service
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
cookie:
  refresh:
    http:
      domain: http://localhost:8000
    token:
      name: refresh-cookie

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

