server:
  port: 8000
spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway-service
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://config-service:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"

cookie:
  refresh:
    http:
      domain: http://localhost:8000
    token:
      name: refresh-cookie
